### ISSUE TITLE
Issue with certificatetemplate

### ISSUE THREAD

**Issue by Obus20** [Crypt32/PSPKI#11]
Hello,

when we use the command get-issuedrequest we sometimes get the certificatetemplate as OID. When we would like to have more properties like the RawCertificate, the property certificatetemplate also shows that rawcertificate.

Can you please help us with that issue?
Our CA runs on a Windows Server 2012 R2 and we are using version  3.2.6 of your Module

Thank you!

**Comment by Crypt32** [comment]
Can you post example output?

**Comment by Obus20** [comment]
Sorry for the late reply to that issue. Here is the example:
`PS C:\script> Get-IssuedRequest -CertificationAuthority $ca | where{$_.RequestId -like "344"}


RequestID             : 344
Request.RequesterName : Example\Wursth
CommonName            : Wursth
NotBefore             : 22.01.2018 15:32:32
NotAfter              : 21.01.2023 15:32:32
SerialNumber          : 150000015816cce1596b147da6000000000158
CertificateTemplate   : 1.3.6.1.4.1.311.21.8.8556969.4048752.15157403.543283.11053858.103
                        .858693.2616764
RowId                 : 344
ConfigString          : server\CA
Table                 : Request`

**Comment by Crypt32** [comment]
What you see when opening this certificate from MMC console on the same machine?

**Comment by Obus20** [comment]
There I can see the correct name and behind that number in brackets.
![2018-01-25 08_21_56-skl659 - remotedesktopverbindung](https://user-images.githubusercontent.com/3807679/35376047-b8989aa2-01a9-11e8-9cda-6f8b263958c5.png)

**Comment by Crypt32** [comment]
Can you run this PowerShell command on the same machine:
`[Security.Cryptography.Oid]"1.3.6.1.4.1.311.21.8.8556969.4048752.15157403.543283.11053858.103
.858693.2616764"`
and tell what it shows?

**Comment by Obus20** [comment]
I got 

`Value                                                       FriendlyName
-----                                                       ------------
1.3.6.1.4.1.311.21.8.8556969.4048752.15157403.543283.110...`

The "FriendlyName" does not show anything.

**Comment by Crypt32** [comment]
Your system fails to resolve OID from Active Directory. I can't tell why. Possible causes:
1) workstation is not joined in AD domain
2) you logged in with local user account
3) workstation cannot connect to domain controller.

**Comment by Crypt32** [comment]
closed as inactive.
