### ISSUE TITLE
Get-CertificationAuthorities (Get-CA) returns $null 

### ISSUE THREAD

**Issue by Anonelectronicmouse** [Crypt32/PSPKI#12]
```
import-module PSPKI
$test = Get-CA
Write-Host $test  # Returns a CertificationAuthority
Invoke-Command -ComputerName . -ScriptBlock {
    import-module PSPKI
    $test = Get-CA
    Write-Host $test # Returns null.
}
```

Same behavior when providing Invoke-command administrator level credentials.

Using 
Windows Server 2012 R2
PowerShell v5.0
PSPKI 3.2.6.0
.net <= 4

**Comment by Crypt32** [comment]
What are your expected results? The command returns $null when there are no registered Enterprise CAs in the forest.

**Comment by Anonelectronicmouse** [comment]
Thanks for the quick response - Expected result is two Certification Authority objects being returned.

**Comment by Crypt32** [comment]
The problem is caused by a "double hop" issue. It is not sufficient to provide administrator credentials. Either, you have to use CredSSP authentication or mark remote machine as trusted for delegation (this can be done in ADUC).

**Comment by Anonelectronicmouse** [comment]
I'm not sure I follow where the second hop is coming from, unless it's within the associated .DLL?

**Comment by Crypt32** [comment]
It comes from domain controller. The code connects to Active Directory to enumerate registered CAs. That is, first hop is when you connect to remote server and second hop is when remote server attempts to contact domain controllers to enumerate CAs.

**Comment by Anonelectronicmouse** [comment]
Awesome; not an issue after all. 
Thanks for the assistance.
