### ISSUE TITLE
Connect-CertificationAuthority sometimes showing CA is IsAvailable False

### ISSUE THREAD

**Issue by EHBrant** [Crypt32/PSPKI#13]
Hello 

I wonder if you can help me with the following issue please,
now and then I will get an issue connecting the CA using Connect-CertificationAuthority -computername CA01 whereby it connects but the status is a follows

isAccessible: False
ServiceStatus: Running

As it says IsAccessible = false, I can then not get or issue requests etc. I presume the ServiceStatus is comming back from a WMI call (please correct me if that is not the case) but what about IsAccessible what is that querying please? does the query use a specific port etc. The odd thing is it works most of the time but evey now and then it will report False so I am trying to work out what I can do on the Windows/Firewall side etc to make it more reliable e.g. True

Thanks very much in advance :)

**Comment by Crypt32** [comment]
> _I presume the ServiceStatus is comming back from a WMI call_

it comes from a Service Control Manager.

Here is the description of this property: http://pkix2.sysadmins.lv/library/html/P_PKI_CertificateServices_CertificateAuthority_IsAccessible.htm

False value indicates that there is no RPC/DCOM connection to CA server. Most likely, it is a firewall issue that blocks RPC/DCOM.

**Comment by EHBrant** [comment]
Thanks very much for the prompt reply. much appreciated :) may be I get some kind of depletion issue on my server after a period of time affecting RCP I will check it out.

Thanks Again
