### ISSUE TITLE
Alias for Get-CertificationAuthority

### ISSUE THREAD

**Issue by fullenw1** [Crypt32/PSPKI#15]
Hi,

To use the cmdlet **Get-CertificationAuthority** we have to type **Get-Certificati** + **Tab** or **Get-Cer** + **Tab** 13 times.
Given that we have to pipe this cmdlet to many other cmdlets from the PSPKI module, could you please implement an alias for the **Get-CertificationAuthority** cmdlet (for example **gca**)?

Thanks in advance and thanks again for you great work!

**Comment by Crypt32** [comment]
My module provides several built-in aliases for commands. Especially, `Get-CertificationAuthority` command has `Get-CA` alias and you can use it. On main project page you can find the list of commands and aliases where available.

In addition, there is no need to call `Get-CertificationAuthority` command each time during a single session. You can easily save CA object in a variable and then pipe it to other commands.

**Comment by fullenw1** [comment]
Good news!
In fact, I typed `Get-Alias Get-CertificationAuthority` and it returned that there is no alias for this cmdlet.
I guess the **Get-Alias** cmdlet only returns aliases declared inside functions...

You are right for the variable. It's even faster because you search for available CAs only once.
Thanks you!

**Comment by Crypt32** [comment]
> I guess the Get-Alias cmdlet only returns aliases declared inside functions...

Get-Alias works in opposite direction: it resolves known alias to unknown fully-qualified command name. That is, if you type `Get-Alias Get-CA` it will return the fully-qualified command name `Get-CertificationAuthority`. It doesn't show possible aliases for known command.

**Comment by fullenw1** [comment]
Damn! You are right! A real newbie error: I forgot the **-Definition** parameter... :-/
`Get-Alias -Definition Get-CertificationAuthority` works fine :-)
Mea Culpa!!!
