### ISSUE TITLE
set-certificatetemplateacl contraint error

### ISSUE THREAD

**Issue by mats99** [Crypt32/PSPKI#17]
Hello there,
thanks for this great module, but I ran into an issue which I was not able to solve. I cannot set template ACLs, it always produces this error no matter what user or group I try. I am Enterprise Admin and have local admin on the CA:

```
PS C:\> import-module pspki
PS C:\> get-certificatetemplateacl -Template WebServer

Path                                    Owner                                   Access
----                                    -----                                   ------
CN=WebServer,CN=Certificate Template... AD\Enterprise Admins                    {PKI.Security.AccessControlEntry2, P...


PS C:\> get-certificatetemplateacl -Template WebServer | Add-CertificateTemplateAcl -User ad\ca-templateadmins -AccessType Allow -AccessMask Read,Write | Set-CertificateTemplateAcl
Set-CertificateTemplateAcl : Exception calling "CommitChanges" with "0" argument(s): "A constraint violation occurred.
"
At line:1 char:158
+ ... k Read,Write | Set-CertificateTemplateAcl
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-CertificateTemplateAcl
```

I am using the latest version of your module on a Windows 2008 R2 enterprise CA with a domain/forest also on 2008 R2 level. I have looked into the source files, added debug output and tried to manually do the steps in the module, but I could not solve this isse. Can you please help me?

**Comment by Crypt32** [comment]
Sorry, I can't repro the issue. Just ran latest public build and it works as expected for me. I can suspect that although you are logged on with Enterprise Admins permissions, the PowerShell console is not running in elevated mode.

**Comment by jandrusk** [comment]
I'm having the same issue as well. I've confirmed that I can perform the same operating through the MMC Certificates Template without a problem. I'm run an elevated Powershell prompt, but keep getting this error.

**Comment by Crypt32** [comment]
That's strange, because I was unable to repro the issue. I tried various command parameters, but everything succeeded for me and never saw this error.

**Comment by jandrusk** [comment]
What's strange now is if I set the user to be the owner of the template and run the command, I don't get an error and it just outputs the full path to the template but does not actually change the ACL on the template.

**Comment by Crypt32** [comment]
I made some research and found that this error may come from insufficient priveleges of the caller. Your attempt to explicitly add user to owner implicitly confirms my findings. This is certainly an issue with priveleges required by AD.

**Comment by Crypt32** [comment]
closing as inactive.
