### ISSUE TITLE
[Feature request] Allow -RowID and -Filter to be used together with Get-DatabaseRow

### ISSUE THREAD

**Issue by jalliot** [Crypt32/PSPKI#20]
Using `Get-DatabaseRow` for the `Attribute` or `Extension` tables does not allow to use at the same time the `-RowID` and `-Filter` parameters (if we specify both, only `-RowID` is taken into account).

There is a way around that by adding another filter for either `AttributeRequestID` or `ExtensionRequestId` but that is not clear and user-friendly.

**Comment by Crypt32** [comment]
Good one. I will look into this.

**Comment by Crypt32** [comment]
Wouldn't you mind if I ask you to check this version of Get-DatabaseRow command: https://github.com/Crypt32/PSPKI/blob/feature-item%2320/PSPKI/Server/Get-DatabaseRow.ps1

I put comments on what I did. It works for me, but would like to know if it works for you and behavior satisifies. If everything is ok, I will commit it to next release.

**Comment by jalliot** [comment]
just tested and it seems to work fine for attributes and extensions but not for requests.
Released version works fine but I get the following error with this updated one (same thing if I add a filter of course):
```
PS > $ca | Get-DatabaseRow -Table Request -RowID 1000
WARNING: Malformed pattern: ' -eq 1000'!
```
This is the only case where it failed though. Even with the CRL table (which I never use normally) I did not have this warning.
One remark, with Request or CRL tables, it might be good to display a warning if a user uses both RowID and Filter parameters, so that he is not surprised that the filter gets ignored in this case (it makes sense of course).

**Comment by Crypt32** [comment]
For CRL and Request tables the behavior is as is. If RowID is specified, then no additional filters ae applied, because RowID means exact row, not a subset rows. And it is explicitly mentioned in command help. I don’t see any reason to use extra filters when you know exact row you want to query.

**Comment by jalliot** [comment]
I completely agree but since the parameters are not exclusive to one another (and shouldn't be because of the attributes and extensions tables), you technically can specify both. It does not make any sense so a warning message could be helpful.

But that's a tiny detail. The problem is more the "malformed pattern" error I got :)
