### ISSUE TITLE
Get-CertificationAuthority 0x800706ba (WIN32: 1722 RPC_S_SERVER_UNAVAILABLE)

### ISSUE THREAD

**Issue by bhushank007** [Crypt32/PSPKI#25]
Hi

We are using a ADCS failover cluster, with only one server being active at a time. I am getting an error when trying to run the command get-certificaitonAuthority i get the following error: I can confirm the RPC service is running and certutil command line is working fine. I have a different system a single enterprise CA in another environment and PSPKI module works fine on that one. Could you please help me resolve this issue. 

Exception calling "EnumEnterpriseCAs" with "2" argument(s): "CCertAdmin::GetCAProperty: The RPC server is unavailable.
0x800706ba (WIN32: 1722 RPC_S_SERVER_UNAVAILABLE)"
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\Server\Get-CertificationAuthority.ps1:14 char:20
+ ... mputerSet" {[PKI.CertificateServices.CertificateAuthority]::EnumEnter ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

PS C:\> $error[0].exception.InnerException.StackTrace
   at CERTADMINLib.CCertAdminClass.GetCAProperty(String strConfig, Int32 PropId, Int32 PropIndex, Int32 PropType, Int32
Flags)
   at PKI.CertificateServices.CertificateAuthority.getCaProperty()
   at PKI.CertificateServices.CertificateAuthority.initialize()
   at PKI.CertificateServices.CertificateAuthority.initializeFromConfigString(String computerName, String name)
   at PKI.CertificateServices.CertificateAuthority..ctor(String computerName, String name)
   at PKI.CertificateServices.CertificateAuthority.EnumEnterpriseCAs(String findType, String findValue)
   at CallSite.Target(Closure , CallSite , Type , String , String )

**Comment by Crypt32** [comment]
Please, show certutil commands you ran and exact PowerShell command you tried.

**Comment by bhushank007** [comment]
Please refer below :-

PS C:\> certutil -ping cb-cvp-ica.cbq.com.qa
Connecting to cb-cvp-ica.cbq.com.qa ...
Server "CBISSUE-CA" ICertRequest2 interface is alive (47ms)
CertUtil: -ping command completed successfully.

PS C:\> Import-Module PSPKI
PS C:\> Get-CertificationAuthority -ComputerName cb-cvp-ica.cbq.com.qa
Exception calling "EnumEnterpriseCAs" with "2" argument(s): "CCertAdmin::GetCAProperty: The RPC server is unavailable.
0x800706ba (WIN32: 1722 RPC_S_SERVER_UNAVAILABLE)"
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\Server\Get-CertificationAuthority.ps1:14 char:20
+ ... mputerSet" {[PKI.CertificateServices.CertificateAuthority]::EnumEnter ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

Please help.

Regards,
Bhushan

**Comment by Crypt32** [comment]
Is `cb-cvp-ica.cbq.com.qa` CA host name or cluster service name?

**Comment by Crypt32** [comment]
What returns this command: `[PKI.CertificateServices.CertificateAuthority]::Ping("cb-cvp-ica.cbq.com.qa")`?

**Comment by bhushank007** [comment]
Please find below the output :-

PS C:\Windows\system32> Import-Module PSPKI
PS C:\Windows\system32> [PKI.CertificateServices.CertificateAuthority]::Ping("cb-cvp-ica.cbq.com.qa")
True

**Comment by bhushank007** [comment]
Hi,
Can you please help us to resolve this issue ?
Thanks in advance.

**Comment by Crypt32** [comment]
Unfortunately, I don't have clustered CA atm for testing. Though, after looking at the code, the only reason why ICertAdmin code may fail is CA name. How long (in characters) is your CA name? Does it include any special/diactrical characters?

**Comment by bhushank007** [comment]
No, Our CA Name does not have any special / diacritical name except '-'. You can find the name from certutil ping response which I shared with you. CA Name is having 10 characters in Total (excluding fully qualified domain name). Is there any way if we can address this ? Appreciate all your help and support.

**Comment by Crypt32** [comment]
That's strange. Ok, let's try direct ICertAdmin call:
```PowerShell
$CertAdmin = new-object -com certificateauthority.admin
$CertAdmin.GetCAProperty("cb-cvp-ica.cbq.com.qa\CBISSUE-CA", 0xb, 0, 1, 0)
```

**Comment by bhushank007** [comment]
Please find below the output -

Import-Module pspki
$CertAdmin = new-object -com certificateauthority.admin
$CertAdmin.GetCAProperty("cb-cvp-ica.cbq.com.qa\CBISSUE-CA", 0xb, 0, 1, 0)

**Comment by bhushank007** [comment]
Sorry - please refer below -

PS C:\> Import-Module pspki
PS C:\> $CertAdmin = new-object -com certificateauthority.admin
PS C:\> $CertAdmin.GetCAProperty("cb-cvp-ica.cbq.com.qa\CBISSUE-CA", 0xb, 0, 1, 0)
1

**Comment by Crypt32** [comment]
If this code works, then `Get-CertificationAuthority` command should work as well. Does the command fails when you explicitly specify cluster name?
```PowerShell
Get-CertificationAuthority -comp "cb-cvp-ica.cbq.com.qa"
```

**Comment by bhushank007** [comment]
Surprisingly, Its started working and I am getting output from Get-CertificationAuthority command. I dont know why it was not working earlier. Thanks for all your support.

**Comment by jamman9000** [comment]
Considering removing the module and fetching the CRL Locations the hard way via registry and replacing the "%1" "%3" etc with their appropriate values that PSPKI module fills for me. Any thoughts?

**Comment by Crypt32** [comment]
>           Considering removing the module and fetching the CRL Locations the hard way via registry and replacing the "%1" "%3" etc with their appropriate values that PSPKI module fills for me. Any thoughts?

can you elaborate?

**Comment by jamman9000** [comment]
> > ```
> >       Considering removing the module and fetching the CRL Locations the hard way via registry and replacing the "%1" "%3" etc with their appropriate values that PSPKI module fills for me. Any thoughts?
> > ```
> 
> can you elaborate?

I just mean that if I can't get this working on the sister CA's then I'll have to rewrite my script to fetch the CRL locations from the registry directly instead of using the module. Looks like this is the only function I'm using the module for right now because of how it replaces the %1 %3 etc in the location string, for me.
