### ISSUE TITLE
Cross Forest Functionality

### ISSUE THREAD

**Issue by eternalyperplxed** [Crypt32/PSPKI#26]
Is there any way that the cmdlets/module can be used to interact with a CA across a 2 way forest trust scenario?  Currently, get-certificationauthority only shows CA's in the local domain.

**Comment by Crypt32** [comment]
There are two options:

1) propagate ADCS information from resource forests to account forest. It is what you do when you organize cross-forest enrollment. In cross-forest enrollment scenario there are no CA servers in account forest, so you copy this information from resource forests (where CAs reside) to account forest. In this case, `Get-CertificationAuthority` cmdlet will see them.

2) use `Connect-CertificationAuthority` cmdlet and specify CA server name in foreign forest. This cmdlet doesn't perform AD lookup and attempts to contact server directly via server name,

**Comment by eternalyperplxed** [comment]
Thank you for the help! We decided to propagate the CA information and that resolved the issue.
