### ISSUE TITLE
Bug when using module on 2008R2/2016 Core (possibly other editions too)

### ISSUE THREAD

**Issue by gmitch64** [Crypt32/PSPKI#30]
There is currently an issue when installing the module on server Core - tested on 2008R2 and 2016, but probably also the same on 2008, 2012 and 2012R2 as well.

If you pull the module from git rather than Gallery, and delete the Server directory, the module installs (and seems to work ) on 2008R2/2016 Core - thanks to Crypt32 for pointing that out (see issue  #29)

When loading the module on core, the Client functions should be exported, and the server ones should not be exported. The help should also be updated to only give examples for the Client functions.

It seems that Install-Module doesn't display any output (other than module configuration errors), so the install process probably shouldn't write a warning that only the client modules are installed, since there's no way to capture that in a script. Possibly something like a Get-PKIModuleStatus should be written to return an object with a $true/$false for .ClientFunctions and .ServerFunctions depending on availability? Given that you already do not export AD  #dependent functions on non domain environments, that could be added too?

**Comment by Crypt32** [comment]
I made appropriate changes. Now, when you install module on a machine without ADCS RSAT, the code doesn't throw exception and exports only client-side functions. In addition, module writes friendly warning message to console about limited functionality.
