### ISSUE TITLE
Specifying properties causes CertificateTemplate to have wrong value

### ISSUE THREAD

**Issue by StevenShockley** [Crypt32/PSPKI#34]
I'm having the following problem when listing certificates.

```powershell
PS C:\> $foo = Get-CertificationAuthority -ComputerName certserver.domain.com | Get-IssuedRequest | select-object -First 1
PS C:\> $foo

RequestID             : 4
Request.RequesterName : DOMAIN\SERVERNAME$
CommonName            :
NotBefore             : 2/17/2017 6:14:57 PM
NotAfter              : 2/17/2018 6:14:57 PM
SerialNumber          : 4a0000000433928ae77eb46c33000000000004
CertificateTemplate   : 1.3.6.1.4.1.311.21.8.14878822.896839.16074912.9548190.15434057.227.8936861.11382353
RowId                 : 4
ConfigString          : certserver.domain.com\CASERVER2
Table                 : Request

PS C:\> $properties = `
>> 'RequestID', `
>> 'CertificateTemplate', `
>> 'CertificateHash', `
>> 'SerialNumber', `
>> 'NotBefore', `
>> 'NotAfter' , `
>> 'DistinguishedName', `
>> 'CommonName', `
>> 'Request.CallerName', `
>> 'Request.RequesterName', `
>> 'Request.RevokedEffectiveWhen', `
>> 'Request.RevokedReason'

PS C:\> $foo = Get-CertificationAuthority -ComputerName certserver.domain.com | Get-IssuedRequest -Property $pro
perties | select-object -First 1
PS C:\> $foo


RequestID                    : 4
Request.RequesterName        : DOMAIN\SERVERNAME$
CommonName                   :
NotBefore                    : 2/17/2017 6:14:57 PM
NotAfter                     : 2/17/2018 6:14:57 PM
SerialNumber                 : 4a0000000433928ae77eb46c33000000000004
CertificateTemplate          : 89 72 8b 64 39 aa dd f7 60 4e 0f 12 ab 61 98 b2 e8 a5 9f ac
CertificateHash              : 89 72 8b 64 39 aa dd f7 60 4e 0f 12 ab 61 98 b2 e8 a5 9f ac
DistinguishedName            :
Request.CallerName           : DOMAIN\SERVERNAME$
Request.RevokedEffectiveWhen :
Request.RevokedReason        :
RowId                        : 4
ConfigString                 : certserver.domain.com\CASERVER2
Table                        : Request

```

Note the CertificateTemplate in the second command has the same value as CertificateHash.  If I do -Property *, it does the same thing but with EnrollmentFlags (which is the next property in the list).

What's going wrong?  I've only been able to duplicate this on one of my two CA servers.

**Comment by Crypt32** [comment]
Is this behavior consistent?

**Comment by StevenShockley** [comment]
Yes, on the one server.  Both servers are Server 2016 if that matters; I can duplicate it against the issuing CA (many requests), I cannot duplicate it on the intermediate CA (few requests).

**Comment by Crypt32** [comment]
Ok, can you try the latest version of PSPKI and confirm if issue still persist?

**Comment by StevenShockley** [comment]
Thanks!  My use of PSPKI in a script seems to be working correctly, but my example above still shows a blank CertificateTemplate.

**Comment by Crypt32** [comment]
Are you accessing the computer via remote desktop or other similar tool (VNC, TeamViewer, etc.)?

Also, can you save results in variable and then check variable contents by accessing objects via indexes? Say: `$var = Get-CertificationAuthority -ComputerName certserver.domain.com | Get-IssuedRequest -Property $properties`
and then access objects: `$var[0]`, where 0 is index in a collection.

Also, what happens when you call properties dierectly, native and synthetic:
`$var[0].CertificateTemplate` and `$var[0].Properties["CertificateTemplate"]`.

**Comment by Crypt32** [comment]
It is not expected. Can you provide results for the rest options and my questions?

**Comment by StevenShockley** [comment]
Sorry.  So, for $var[0] I get:

RequestID                    : 81
Request.RequesterName        : DOMAIN\COMPUTERNAME$
CommonName                   : COMPUTERNAME.DOMAIN.com
NotBefore                    : 2/28/2017 11:24:53 PM
NotAfter                     : 2/28/2018 11:24:53 PM
SerialNumber                 : 11fb7b19000100000051
CertificateTemplate          :
CertificateHash              : 35 82 f1 fe 97 a0 30 08 01 25 57 7f e2 1d 97 0c 66 0f 31 e9
DistinguishedName            : CN=COMPUTERNAME.DOMAIN.com
Request.CallerName           : DOMAIN\COMPUTERNAME$
Request.RevokedEffectiveWhen :
Request.RevokedReason        :
RowId                        : 81
ConfigString                 : PADC2CERT2.DOMAIN.com\BCMCERT2
Table                        : Request
Properties                   : {[RequestID, 81], [Request.RequesterName, DOMAIN\COMPUTERNAME$], [CommonName,
                               COMPUTERNAME.DOMAIN.com], [NotBefore, 2/28/2017 11:24:53 PM]...}`

I'm connected via RDP to my admin workstation, and the CA is on anther machine.  Not sure if it matters, but my account and workstation are in one forest, and the CA is in a different forest with a two-way trust.

I tried running this on the CA itself (using an account in that forest, via RDP) and got the same results.

**Comment by Crypt32** [comment]
Ok, I will check what is going on with certificate template property. But you mentioned issues with other properties (EnrollmentFlags). Can you confirm that when accessing them via variable works as expected?

**Comment by StevenShockley** [comment]
Sorry, EnrollmentFlags works correctly, I just wanted to show that it was copying the data from the previous field, whatever that field was.  The only attribute I've noticed a problem with is CertificateTemplate.  Thanks!

**Comment by Crypt32** [comment]
Regarding `CertificateTemplate` synthetic property, it was broken during code change. Synthetic properties are obsolete and [as of now] you should use `Properties` property collection to retrieve particular properties.

Issue with wrong values in other properties is console bug when accessing it via RDP. There are known issues when console host messes with it's content when working in remote desktop sessions.

**Comment by StevenShockley** [comment]
I just noticed something else interesting.  Since this is cross-forest, a bunch of the OIDs don't resolve.  (Even in-forest, some OIDs don't resolve if the template has been deleted.)  It looks like CertificateTemplate is only null when it can't resolve the OID.  For example:

`write-output "rqct: $($request.CertificateTemplate) prop: $($request.Properties['CertificateTemplate'])"`

returns:
`rqct:  prop: 1.3.6.1.4.1.311.21.8.[truncated].4215684`
`rqct: CAExchange prop: CAExchange`

**Comment by StevenShockley** [comment]
Okay, so I should just use `Properties` from now on?  Works for me.  Thanks!

**Comment by Crypt32** [comment]
Yes, like I said, it was broken here: https://github.com/Crypt32/PSPKI/blob/39434c6950157844b52b82e25cb52d8925ea2d22/PSPKI/Server/Get-RequestRow.ps1#L125
I moved the coude outside of `while` loop, but didn't change internal (for loop) variables. Can you create separate issue for `CertificateTemplate` property synthetic property? I'm going to close this issue, because multiple issues were discussed here and only one is a bug.

**Comment by Crypt32** [comment]
> Okay, so I should just use Properties from now on? Works for me. Thanks!

yes. It is mentioned in release notes: https://www.sysadmins.lv/projects/pspki/release-notes-for-pspki-v330.aspx and in blog post: https://www.sysadmins.lv/blog-en/powershell-pki-module-v330-is-out.aspx

I will keep noteproperty support only for PowerShell and display purposes. However, when operating with properties (using value in scripts), you shall use `Properties` property collection.
