### ISSUE TITLE
Importing the module on recent PowerShell versions fails with Update-TypeData errors

### ISSUE THREAD

**Issue by pronichkin** [Crypt32/PSPKI#39]
OS: Windows 10 version 1803—or corresponding Windows Server version
PowerShell version: built-in (5.1.17134.1)

Trying to import the module fails with multitude of the following errors:

`Update-TypeData : Error in TypeData "System.Security.Cryptography.X509Certificates.X509Certificate2": The member ResolvedExtensions is already present.
`

### workaround
comment out (or remove) the following block in `.psm1` file

`if ($PSVersionTable["PSVersion"].Major -gt 2) {
    try {
        Update-TypeData $PSScriptRoot\Types\PSPKI.Types.ps1xml
        Update-FormatData $PSScriptRoot\Types\PSPKI.Format.ps1xml
    } catch { }
}
`

This works, but breaks digital signature, hence not very useful.

**Comment by Crypt32** [comment]
Fixed in: https://github.com/Crypt32/PSPKI/commit/14fe2ebebf4998de49e76989694e6e78c4511fed
