### ISSUE TITLE
New-SelfSignedCertificateEx not setting issuer and subject

### ISSUE THREAD

**Issue by johlju** [Crypt32/PSPKI#42]
Trying to generate a certificate using the following.

```powershell
$newSelfSignedCertificateExParameters = @{
    Subject            = "CN=DscEncryptionCert"
    EKU                = 'Document Encryption'
    KeyUsage           = 'KeyEncipherment, DataEncipherment'
    SAN                = 'DscEncryptionCert'
    FriendlyName       = 'DSC Credential Encryption certificate'
    Exportable         = $true
    StoreLocation      = 'LocalMachine'
    KeyLength          = 2048
    ProviderName       = 'Microsoft Enhanced Cryptographic Provider v1.0'
    AlgorithmName      = 'RSA'
    SignatureAlgorithm = 'SHA256'
}

$certificate = New-SelfSignedCertificateEx @newSelfSignedCertificateExParameters
```

But the result look like this (issuer and subject is blank).

![image](https://user-images.githubusercontent.com/7189721/41959074-46b3153c-79ec-11e8-98c3-08e21bdeacae.png)

Am I using it wrong?

**Comment by Crypt32** [comment]
Yes, my bad. I haven't updated the help file to reflect correct usage of SAN extension. SAN field is formed as follows: `type:value`, where `type` is a type SAN entry and `value` is string value of the SAN entry. Possible types are:

- `dn` (directory name in X.500 format)
- `dns` (DNS name)
- `ip` (ipv4/ipv6 address)
- `email` (RFC822 email)
- `upn` (user principal name, syntax is same as for email)
- `guid` - (globally unique identifier)
- `url` - (standard url)

for example if you want to add SAN entry as DNS name, the syntax is `dns:DscEncryptionCert`, if it is user principal name, then:  use this syntax: `dns:DscEncryptionCert`.
