### ISSUE TITLE
Set-CertificateExtension issue with inexistent OID.Format() method

### ISSUE THREAD

**Issue by jalliot** [Crypt32/PSPKI#44]
Hello,
There is a new bug since v3.3 in the Set-CertificateExtension function. 3 times in this function you are calling an inexistent Format() method on the OID objects.
This result in the try/catch to be triggered and the whole function to be exited, which is not good when we have more than 1 extension to set at once

**Comment by Crypt32** [comment]
This method exists as .NET extension method. This syntax would work in c#, but must be called differently in PowerShell.
