### ISSUE TITLE
Test-WebServerSSL exception

### ISSUE THREAD

**Issue by georg-x** [Crypt32/PSPKI#47]
I'm managing a set of servers where Test-WebServerSSL brings an exception no matter where I try to connect to. The Problem looks exactly like I'm trying to access a port, where either SSL isn't in use, or the port is not reachable at all. But I've verified multiple times that the port is reachable and and via openssl also a valid connections is established.

```
PS C:\> Test-WebServerSSL -url server.contoso.tld -port 80
Exception calling "SendRequest" with "0" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\pspki\Client\Test-WebServerSSL.ps1:26 char:2
+     $Response.SendRequest()
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

```

I'm propsing a more specific error message for that error. Either it should tell me, the port is not reachable, or that the port didn't support any SSL/TLS. Or even more details on what's the problem at all.!

**Comment by Crypt32** [comment]
This is a bug and occurs only when underlying connection fails. This line: https://github.com/Crypt32/pkix.net/blob/master/PKI/Web/WebSSL.cs#L132
has missing `null` check for response object. It can be null only when exception is thrown at this line: https://github.com/Crypt32/pkix.net/blob/master/PKI/Web/WebSSL.cs#L108

Going to fix this in next release.

**Comment by georg-x** [comment]
Thank you very much! More details on error will surley help!
ATM I'm trying to understand why telnet and openssl are able to connect a server/port combination but Test-WebServerSSL is not...
