### ISSUE TITLE
Refactor Write-Host and Write-Warning usage

### ISSUE THREAD

**Issue by TDabasinskas** [Crypt32/PSPKI#5]
As discussed in https://github.com/Crypt32/PSPKI/issues/4, the following functions need to be updated, to get rid of `Write-Host` and `Wriye-Warning` (where it is used incorrectly):<br /><br />\* Approve-CertificateRequest<br />\* Get-RequestRow<br />\* Remove-CAKRACertificate<br />\* Revoke-Certificate<br />\* Remove-CertificateEnrollmentPolicyService<br />\* Remove-CertificateEnrollmentService<br />\* Remove-DatabaseRow<br />\* Deny-CertificateRequest<br />\* Add-CertificateEnrollmentService<br />\* Add-CertificateEnrollmentPolicyService<br />\* Add-CertificateTemplateAcl<br /><br />Thank you.

**Comment by Crypt32** [comment]
Thanks for report. I will follow this list to improve error behavior in these commands.

**Comment by Crypt32** [comment]
The work is in progress in this branch: https://github.com/Crypt32/PSPKI/tree/feature-WriteHostCompliance
