### ISSUE TITLE
Add support for -ne operator on -Filter

### ISSUE THREAD

**Issue by milesgratz** [Crypt32/PSPKI#53]
Feature request: Add support for -ne operator on -Filter for various cmdlets like `Get-IssuedRequest`

> Possible operators are:
> -eq (equal to) - the value in the <value> field equals to a value stored in the certificate request property.
> -le (less or equal to) - the value in the <value> field is less or equal to a value stored in the certificate request property. See below about operator behavior with string qualifiers.
> -lt (less than) - the value in the <value> field is less then a value stored in the certificate request property. See below about operator behavior with string qualifiers.
> -ge (greater or equal to) - the value in the <value> field is greater or equal to a value stored in the certificate request property. See below about operator behavior with string 
> qualifiers.
> -gt (greater than) - the value in the <value> field is greater than a value stored in the certificate request property. See below about operator behavior with string qualifiers.

**Comment by Crypt32** [comment]
Unfortunately, there is no available API or other viable way to mimic this operator, therefore I can't do anything here.

**Comment by milesgratz** [comment]
Ah ok! Cheers 👍
