### ISSUE TITLE
Add-AdCertificate -Certificate

### ISSUE THREAD

**Issue by bencoremans** [Crypt32/PSPKI#54]
Get-AdPkiContainer -ContainerType RootCA | Add-AdCertificate -Certificate $cert
Unable to find type [SysadminsLV.PKI.Management.ActiveDirectory.DsPkiCertContainerDsAiaContainer].
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.0.0\Client\Add-AdCertificate.ps1:17 char:34
+ ... ntainer -is [SysadminsLV.PKI.Management.ActiveDirectory.DsPkiCertCont ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SysadminsLV.PKI...rDsAiaContainer:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound 

I changed line 17:
original:
if ($Adcontainer -is [SysadminsLV.PKI.Management.ActiveDirectory.DsPkiCertContainer.DsAiaContainer]) {
change in:
if ($Adcontainer -is [SysadminsLV.PKI.Management.ActiveDirectory.DsAiaContainer]) {
After this change the certificate can be placed in AD.

**Comment by Crypt32** [comment]
Pushed patch release in PowerShell Gallery as well.
