### ISSUE TITLE
Error with Get-EnterprisePKIHealthStatus

### ISSUE THREAD

**Issue by gaudes** [Crypt32/PSPKI#55]
Hi,

when running Get-EnterprisePKIHealthStatus I get error messages:

```
Ausnahme beim Aufrufen von "DecodeGeneralizedTime" mit 1 Argument(en):  "Input data is not valid ASN-encoded GENERALIZED TIME."
In C:\Program Files\WindowsPowerShell\Modules\pspki\3.4.0.1\Server\Get-EnterprisePKIHealthStatus.ps1:357 Zeichen:33
+ ...             [SysadminsLV.Asn1Parser.Asn1Utils]::DecodeGeneralizedTime ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidDataException
```
My first thought was that it may be a problem with german language. But I've done some debugging. 

In the lines causing the error there is a try-catch-block. First call is 

```[SysadminsLV.Asn1Parser.Asn1Utils]::DecodeUTCTime($e.RawData)```

When this fails, the catch block is running which is causing the error. I've done some debug outputs in the code. It runs in the catch block due to this error:

```Fehler beim Aufrufen der Methode, da [SysadminsLV.Asn1Parser.Asn1Utils] keine Methode mit dem Namen "DecodeUTCTime" enthält. ```

Translated it means "There is no method "DecodeUTCTime" in [SysadminsLV.Asn1Parser.Asn1Utils]

Any ideas ?

Thanks and regards,

Ralf

**Comment by Crypt32** [comment]
Indeed, the method no longer exist. As a temporary fix, replace line 355 in Get-EnterprisePKIHealthStatus.ps1 file:
`[SysadminsLV.Asn1Parser.Asn1Utils]::DecodeUTCTime($e.RawData)`
to this one:
`(New-Object SysadminsLV.Asn1Parser.Universal.Asn1UtcTime -arg @(,($e.RawData))).Value`

**Comment by gaudes** [comment]
Thank you for the very fast answer, this fixed the error.
Regards, Ralf
