### ISSUE TITLE
Question - help for 

### ISSUE THREAD

**Issue by sorset** [Crypt32/PSPKI#57]
I have made CA Root certificate with "New-SelfSignedCertificateEx".
My problem is how to create domain/server/intermediate certificate which is slave to root?

Can you help me?
I have made CA Root Authority certificate. I use power shell instead makecert.exe command. I added into my trusted zone.

Now I want to create server CN=domain certificate which is extend CA authority.  I need to sign and deploy on my IIS. How to do that with ps1 language?

|-----"My ROOT CA" 
            |
            |--------"My Slave" (DNS CN=domain.local)

I thing I need to set "Issued to" and "Issued by".

"My ROOT CA" 
   Issued to - My ROOT CA
   Issued by - My ROOT CA

 "My Slave" 
   Issued to - My ROOT CA
   Issued by - domain.local

https://stackoverflow.com/posts/53214625/edit

I see that this script provides a way to create a CA cert with IsCA option, but how do I create a self-signed certificate signed by that CA cert ? I didnt see nay IsssuerCert or Signer Cert option.

 Is it possible to update this script for that capability ? It would be helpful as I can trust a single CA cert in our team's local machines for development and test environments.

**Comment by Crypt32** [comment]
`New-SelfSignedCertificateEx` has `-Issuer` parameter: https://www.sysadmins.lv/projects/pspki/New-SelfSignedCertificateEx.aspx

You pass issuer certificate with private key (an instance of `X509Certificate2` object) and new certificate will be signed by this issuer. When using `-Issuer` parameter:

- `Issuer` field of new certificate is filled with `Subject` field value of issuer certificate
- `Authority Key Identifier` extension is added to new certificate and its value matches `Subject Key Identifier` extension value of issuer certificate.

Note, that for better discoverability you may need to manually add `Authority Information Access` extension to leaf certificate. Also, for revocation purposes, you may need to add a `CRL Distribution Points` extension and/or add appropriate access method to `Authority Information Access` to provide OCSP server locations. These extensions are not added automatically.

**Disclaimer**: this approach is not production-ready. You MUST use standard CA software only in production. No OpenSSL, certreq, certutil, PowerShell shall be used in production. Only for basic test purposes.

**Comment by sorset** [comment]
Can I do with these steps?#Create Root CA CertNew-SelfSignedCertificateEx ....# Sign with Module: pkiclient and parameter -SignerNew-SelfSignedCertificate -Signer "CertCA.pfx"More info:https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-psNew-SelfSignedCertificate   [-SecurityDescriptor <FileSecurity>]   [-TextExtension <String[]>]   [-Extension <X509Extension[]>]   [-HardwareKeyUsage <HardwareKeyUsage[]>]   [-KeyUsageProperty <KeyUsageProperty[]>]   [-KeyUsage <KeyUsage[]>]   [-KeyProtection <KeyProtection[]>]   [-KeyExportPolicy <KeyExportPolicy[]>]   [-KeyLength <Int32>]   [-KeyAlgorithm <String>]   [-SmimeCapabilities]   [-ExistingKey]   [-KeyLocation <String>]   [-SignerReader <String>]   [-Reader <String>]   [-SignerPin <SecureString>]   [-Pin <SecureString>]   [-KeyDescription <String>]   [-KeyFriendlyName <String>]   [-Container <String>]   [-Provider <String>]   [-CurveExport <CurveParametersExportType>]   [-KeySpec <KeySpec>]   [-Type <CertificateType>]   [-FriendlyName <String>]   [-NotAfter <DateTime>]   [-NotBefore <DateTime>]   [-SerialNumber <String>]   [-Subject <String>]   [-DnsName <String[]>]   [-SuppressOid <String[]>]   [-HashAlgorithm <String>]   [-AlternateSignatureAlgorithm]   [-TestRoot]   [-Signer <Certificate>]   [-CloneCert <Certificate>]   [-CertStoreLocation <String>]   [-WhatIf]   [-Confirm]   [<CommonParameters>]Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Vadims Podans <notifications@github.com> Date: 11/9/18  11:52  (GMT+02:00) To: Crypt32/PSPKI <PSPKI@noreply.github.com> Cc: Sors <sorset@qq.com>, Author <author@noreply.github.com> Subject: Re: [Crypt32/PSPKI] Question - help for  (#57) New-SelfSignedCertificateEx has -Issuer parameter: https://www.sysadmins.lv/projects/pspki/New-SelfSignedCertificateEx.aspx
You pass issuer certificate with private key (an instance of X509Certificate2 object) and new certificate will be signed by this issuer. When using -Issuer parameter:

Issuer field of new certificate is filled with Subject field value of issuer certificate
Authority Key Identifier extension is added to new certificate and its value matches Subject Key Identifier extension value of issuer certificate.

Note, that for better discoverability you may need to manually add Authority Information Access extension to leaf certificate. Also, for revocation purposes, you may need to add a CRL Distribution Points extension and/or add appropriate access method to Authority Information Access to provide OCSP server locations. These extensions are not added automatically.
Disclaimer: this approach is not production-ready. You MUST use standard CA software only in production. No OpenSSL, certreq, certutil, PowerShell shall be used in production. Only for basic test purposes.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Crypt32/PSPKI","title":"Crypt32/PSPKI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Crypt32/PSPKI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Crypt32 in #57: `New-SelfSignedCertificateEx` has `-Issuer` parameter: https://www.sysadmins.lv/projects/pspki/New-SelfSignedCertificateEx.aspx\r\n\r\nYou pass issuer certificate with private key (an instance of `X509Certificate2` object) and new certificate will be signed by this issuer. When using `-Issuer` parameter:\r\n\r\n- `Issuer` field of new certificate is filled with `Subject` field value of issuer certificate\r\n- `Authority Key Identifier` extension is added to new certificate and its value matches `Subject Key Identifier` extension value of issuer certificate.\r\n\r\nNote, that for better discoverability you may need to manually add `Authority Information Access` extension to leaf certificate. Also, for revocation purposes, you may need to add a `CRL Distribution Points` extension and/or add appropriate access method to `Authority Information Access` to provide OCSP server locations. These extensions are not added automatically.\r\n\r\n**Disclaimer**: this approach is not production-ready. You MUST use standard CA software only in production. No OpenSSL, certreq, certutil, PowerShell shall be used in production. Only for basic test purposes."}],"action":{"name":"View Issue","url":"https://github.com/Crypt32/PSPKI/issues/57#issuecomment-437308171"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-437308171",
"url": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-437308171",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Crypt32/PSPKI] Question - help for  (#57)",
"sections": [
{
"text": "",
"activityTitle": "**Vadims Podans**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Crypt32",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Crypt32/PSPKI\",\n\"issueId\": 57,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Crypt32/PSPKI\",\n\"issueId\": 57\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-437308171"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408327941\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Crypt32** [comment]
Sorry, the message is unreadable.

**Comment by sorset** [comment]
My bad. Please check attached image Thanks.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Vadims Podans <notifications@github.com> Date: 11/17/18  22:33  (GMT+02:00) To: Crypt32/PSPKI <PSPKI@noreply.github.com> Cc: Sors <sorset@qq.com>, Author <author@noreply.github.com> Subject: Re: [Crypt32/PSPKI] Question - help for  (#57) Sorry, the message is unreadable.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Crypt32/PSPKI","title":"Crypt32/PSPKI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Crypt32/PSPKI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Crypt32 in #57: Sorry, the message is unreadable."}],"action":{"name":"View Issue","url":"https://github.com/Crypt32/PSPKI/issues/57#issuecomment-439645686"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-439645686",
"url": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-439645686",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Crypt32/PSPKI] Question - help for  (#57)",
"sections": [
{
"text": "",
"activityTitle": "**Vadims Podans**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Crypt32",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Crypt32/PSPKI\",\n\"issueId\": 57,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Crypt32/PSPKI/issues/57#issuecomment-439645686"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408327941\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Crypt32** [comment]
There is no attachments when replying via email. Try to post via web site, not email.

**Comment by sorset** [comment]
![screenshot_20181117-224752_email](https://user-images.githubusercontent.com/12751190/48666085-64796600-eac3-11e8-9722-fc56d604c6c2.jpg)
