### ISSUE TITLE
{"The term 'Describe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}

### ISSUE THREAD

**Issue by zm44** [Crypt32/PSPKI#66]
Never faced this issue for past 2 weeks.
I am importing an offline version of this library which i fetched two weeks ago. 
Should I always use the latest?
the machine where I am using this library does not have Internet connection.

Stack Trace --
ScriptStackTrace = "at <ScriptBlock>, C:\\Users\\testuser\\Desktop\\Scripts\\PSPKI\\PSPKI.tests.ps1: line 7\r\nat <ScriptBlock>, C:\\Users\\testuser\\Desktop\\Scripts\\PSPKI\\PSPKI.psm1: line 126\r\nat <ScriptBlock>, C:\\Users\\testuser\\Desktop\\Scripts\\PSPKI\\PSPKI.psm1: line...

**Comment by Crypt32** [comment]
Where did you get the offline version of the module? You need to remove the `PSPKI.tests.ps1` file from your folder.

**Comment by zm44** [comment]
since the system i am running it on does not have an internet connection..i got the zip file from github repo and importing it in my script.
Removing "PSPKI.tests.ps1" helped.
I do not see the error anymore.
Thank you.
