### ISSUE TITLE
Set-CAKRACertificate changes my certificates thumbprint

### ISSUE THREAD

**Issue by vrdse** [Crypt32/PSPKI#7]
I use PSPKI in Windows 2016 Core test environment. I know Windows 2016 is not in the list of supported OS, but I thought it's worth a try. ;)

The CA is newly installed, I do not have any KRA on this system added. I want to you PSPKI to add a KRA. The KRA certificate is already issued by another CA. The certificate is valid and trusted. It has the thumbprint (sample) 0F75CCFC39455ABD64851AAEF50D202B7580C3A7.

`$CA | Get-CAKRACertificate`

Certificate: Empty

`$KRACert = Get-ADKRACertificate -Subject "CN=$CAKRA*"`

$KRACert is from the type System.Security.Cryptography.X509Certificates.X509Certificate2 and contains the correct certificate, with the thumbprint 0F75CCFC39455ABD64851AAEF50D202B7580C3A7

`$KRA = $CA | Add-CAKRACertificate -Certificate $KRACert`

$KRA is from the type PKI.CertificateServices.KRA and the thumbprint is still 0F75CCFC39455ABD64851AAEF50D202B7580C3A7

`$KRA | Set-CAKRACertificate -RestartCA
 $CA | Get-CAKRACertificate`

After using Set-CAKRACertificate, the thumbprint suddenly changes! The thumbprint is now (sample) 5106DD2F848595803C817E72E1205A0AA1EF67C7. The subject, serial number etc. however is as expected (=correct). But, because of the wrong thumbprint, the certificate is, of course, invalid. 
I tried to add Get-CAKRACertificate, Remove-CAKRACertificate etc. to my command. But still, in every scenario, as soon as I use Set-CAKRACertificate, the thumbprint changes to the wrong value (its always the same wrong value).

If I use the Certification Authority console I can add the Key Recovery Agent successfully (and valid ;) ).

**Comment by Crypt32** [comment]
I will take a look. Though unlikely that earlier than next week.

**Comment by vrdse** [comment]
@Crypt32 , please let me know if you need further information or I can support you anyhow

**Comment by Crypt32** [comment]
I don't think I need more information right now. I'm able to repro the issue and trying to figure out what happens.

**Comment by Crypt32** [comment]
Found the issue. I forgot to make casting in DER converter. Tested and it works as expected.

**Comment by vrdse** [comment]
I can confirm that it's working now. Thank you, Vadims!
