### ISSUE TITLE
Install-CertificationAuthority missing on Server2016

### ISSUE THREAD

**Issue by tansei** [Crypt32/PSPKI#72]
Hi !
version 3.4.1.0 grabbed from gallery, does not list the Install-CertificationAuthority among the available cmdlets.
I foresee the following reasons:
* it is abandoned kind of relict from the past which was kind of replacement for certsrv in 2008R2 days
* it was replaced by the commandlets available in the operating system itself
* it does not make sense to make it available on 2016 where the DSC is capable doing similar things

the strange thing is that this commandlet is exposed on windows7 client, which made me wonder why, and is it expected behavior.
* should this module be used for the ADCS role installation, or it is rather to be used to manage certificates with all the other commandlets which it brings to the table, and all the goodies available there ?

Thank you !

**Comment by Crypt32** [comment]
> it was replaced by the commandlets available in the operating system itself

this is the case. Starting with Windows Server 2012, OS ships a built-in cmdlet with exact functionality and I decided to no install the command on new platforms. Every online help page includes operating system support: https://www.sysadmins.lv/projects/pspki/Install-CertificationAuthority.aspx

**Comment by tansei** [comment]
thank you ! this was the confirmation which I've been looking for, once analyzed the Install-CertificationAuthority.ps1 file.
cheers from PL!
