### ISSUE TITLE
PSPKI 3.4.1.0 does not auto-load

### ISSUE THREAD

**Issue by andhag** [Crypt32/PSPKI#74]
Been trying to manually install PSPKI in an offline environment.

I place the module-files inside a `PSPKI` folder under `C:\Program Files\WindowsPowershell\Modules` and expect to be able to run commands using powershell, but the module is not available.

I CAN `Import-Module PSPKI` and it is listed under `Get-Module -ListAvailable`.

Tests with version 3.3.0.0 show it works as intended.

**Comment by Crypt32** [comment]
I'm not responsible for module autoload. If you can execute commands after `Import-Module PSPKI`, then module is installed correctly. Autoload depends on PowerShell version. On some versions, the module is autoloaded, on others not.

**Comment by andhag** [comment]
Ok! Thanks for your quick response! Running powershell 5.0 and will look into autoloading when my certificate templates are up and running.
