### ISSUE TITLE
Get-CACryptographyConfig doesn't return 'PublicKeyAlgorithm' and 'HashingAlgorithm' when provider is the 'nCipher Security World Key Storage Provider' or 'Microsoft Software Key Storage Provider'

### ISSUE THREAD

**Issue by MPenny-nCipher** [Crypt32/PSPKI#75]
Hello

Setup: ADCS Enterprise Issuing CA running on Windows Server 2016 Standard

When running 'Get-CACryptographyConfig' against a CA locally, the output does not display the configured 'PublicKeyAlgorithm' or 'HashingAlgorithm' when using the 'nCipher Security World Key Storage Provider' (i.e. 3rd party HSM KSP). E.g.:

```
PS C:\Users\Administrator.PKITRAINING> Get-CertificationAuthority | Get-CACryptographyConfig


Name                        : PKI Training Lab Issuing CA
DisplayName                 : PKI Training Lab Issuing CA
ComputerName                : IssuingCA.PKITRAINING.LAB
PublicKeyAlgorithm          : System.Security.Cryptography.Oid
HashingAlgorithm            : System.Security.Cryptography.Oid
ProviderName                : nCipher Security World Key Storage Provider
AlternateSignatureAlgorithm : False
ProviderIsCNG               : True
IsModified                  : False
```

I had expected to see output such as 'RSA' for the 'PublicKeyAlgorithm' and 'SHA256' for the 'HashingAlgorithm' respectively.

I had assumed this might be an issue with reading/querying the 3rd party KSP but when running the same command against a CA using the 'Microsoft Software Key Storage Provider', the output is:

```
PS C:\Users\Administrator> Connect-CertificationAuthority | Get-CACryptographyConfig

Name                        : Issuing CA 2 - Software
DisplayName                 : Issuing CA 2 - Software
ComputerName                : IssuingCA2.PKITRAINING.LAB
PublicKeyAlgorithm          : System.Security.Cryptography.Oid
HashingAlgorithm            : System.Security.Cryptography.Oid
ProviderName                : Microsoft Software Key Storage Provider
AlternateSignatureAlgorithm : False
ProviderIsCNG               : True
IsModified                  : False
```

So, is this a bug or have I misinterpreted what the command is supposed to do and output, please?

Thanks.

**Comment by MPenny-nCipher** [comment]
I have also tested this with an Enterprise Issuing CA on Windows Server 2012 R2 using the 'nCipher Security World Key Storage Provider'. Same issue:

```
PS C:\Users\Administrator.PKITRAINING> Connect-CertificationAuthority | Get-CACryptographyConfig


Name                        : PKI Training Lab Issuing CA Win2k12R2
DisplayName                 : PKI Training Lab Issuing CA Win2k12R2
ComputerName                : IssuingCA3.PKITRAINING.LAB
PublicKeyAlgorithm          : System.Security.Cryptography.Oid
HashingAlgorithm            : System.Security.Cryptography.Oid
ProviderName                : nCipher Security World Key Storage Provider
AlternateSignatureAlgorithm : False
ProviderIsCNG               : True
IsModified                  : False
```

**Comment by Crypt32** [comment]
There is nothing wrong with reading 3rd party providers, it is how PowerShell formats objects. In PowerShell 3.0 and 4.0 PowerShell shipped custom formats for OIDs, but it was broken in PowerShell 5.x+. You still can get values:

```
$config = Connect-CertificationAuthority | Get-CACryptographyConfig
$config.PublicKeyAlgorithm
$config.HashingAlgorithm
```
and you will see expected values.

**Comment by MPenny-nCipher** [comment]
Thank you. That works as you suggest. Apologies for the erroneous report.

**Comment by Crypt32** [comment]
No problems. I will see if I can add custom formatting for OID objects. If you don't mind, open new issue on custom OID formats in newer PowerShell versions and I will close this issue.
