### ISSUE TITLE
Powershell Gallery

### ISSUE THREAD

**Issue by ld0614** [Crypt32/PSPKI#9]
Firstly thanks for such an awesome module, I was wondering with the imminent shutdown of codeplex is the plan to move the distribution of PSPKI over to the PowerShell gallery?  

From a consumer perspective this would be awesome as it significantly reduces the complexities of setting up a new client as the installation of PowerShell Gallery modules can be easily scripted.

**Comment by Crypt32** [comment]
With the CodePlex shutdown, I will be forced to move to PS Gallery.

**Comment by ld0614** [comment]
Thanks for the update

**Comment by hrboyceiii** [comment]
I just looked today for this module on PSGallery and didn't find it. Is there a timeline for publishing it to the gallery?

Thanks

**Comment by Crypt32** [comment]
Next week.

**Comment by Crypt32** [comment]
Delivered: https://www.powershellgallery.com/packages/PSPKI/3.2.7.0

**Comment by hrboyceiii** [comment]
Thank you so much!!! Unrelated but do you have any recommendations on online resources for working with ADCS specifically enrollment web services? Everything seems to be focused on administration or implementation but now that actual use. 

Thanks again

**Comment by Crypt32** [comment]
Sorry, I have nothing to recommend on this. Though, whitepapers include sections with operational processes (enrollment).
